import { defaultImages } from "./images";

export const userProfile = [{
    id: "u123456",
    name: "Juan Pérez",
    email: "a@gmail.com",
    phone: "+34 600 123 456",
    city: "Santiago",
    region: "metropolitana",
    country: "Chile",
    rating: {
        average: 4.2,
        total: 85,
        distribution: {
            1: 3,
            2: 5,
            3: 12,
            4: 25,
            5: 40,
        },
    },
    products: [{
            id: "p001",
            title: "Chaqueta de mezclilla vintage",
            price: 19990,
            images: [defaultImages.products[0]],
            status: "vendido",
            rating: {
                average: 4.2,
                total: 85
            }
        },
        {
            id: "p002",
            title: "Polera oversize negra",
            price: 5990,
            images: [defaultImages.products[1]],
            status: "vendido",
            rating: {
                average: 4.2,
                total: 85
            }
        },
    ],
    favorites: [{
            id: "p003",
            title: "Pantalón cargo verde militar",
            price: 11990,
            images: [defaultImages.products[2]],
            seller: {
                id: "u003",
                name: "Valentina Díaz",
                email: "valed@mail.com",
                phone: "+56922334455",
                rating: 4.9,
                totalRatings: 40
            }
        },
        {
            id: "p004",
            title: "Zapatillas Converse Chuck 70",
            price: 24990,
            images: [defaultImages.products[3]],
            seller: {
                id: "u004",
                name: "Diego López",
                email: "dlopez@mail.com",
                phone: "+56933221144",
                rating: 4.2,
                totalRatings: 7
            }
        },
    ],
}, ];

export const AllProducts = [{
        id: "p001",
        title: "Chaqueta de mezclilla vintage",
        description: "Chaqueta Levi's clásica de los 90s en excelente estado.",
        price: 19990,
        size: "L",
        category: "chaquetas",
        images: [defaultImages.products[0], defaultImages.products[1]],
        status: "vendido",
        seller: {
            id: "u123456",
            name: "Juan Pérez",
            email: "a@gmail.com",
            phone: "+34 600 123 456",
            rating: 4.2,
            totalRatings: 85
        },
        userRating: null,
    },
    {
        id: "p002",
        title: "Polera oversize negra",
        description: "Polera H&M oversize 100% algodón, poco uso.",
        price: 5990,
        size: "M",
        category: "poleras",
        images: [defaultImages.products[1], defaultImages.products[2]],
        status: "vendido",
        seller: {
            id: "u123456",
            name: "Juan Pérez",
            email: "a@gmail.com",
            phone: "+34 600 123 456",
            rating: 4.2,
            totalRatings: 85
        },
        userRating: null,
    },
    {
        id: "p003",
        title: "Pantalón cargo verde militar",
        description: "Pantalón estilo urbano, varios bolsillos. Marca Zara.",
        price: 11990,
        size: "S",
        category: "pantalones",
        images: [defaultImages.products[2], defaultImages.products[3]],
        status: "disponible",
        seller: {
            id: "u003",
            name: "Valentina Díaz",
            email: "valed@mail.com",
            phone: "+56922334455",
            rating: 4.9,
            totalRatings: 40,
        },
        userRating: null,
    },
    {
        id: "p004",
        title: "Zapatillas Converse Chuck 70",
        description: "Zapatillas en buen estado, uso moderado.",
        price: 24990,
        size: "42",
        category: "zapatos",
        images: [defaultImages.products[3], defaultImages.products[4]],
        status: "disponible",
        seller: {
            id: "u004",
            name: "Diego López",
            email: "dlopez@mail.com",
            phone: "+56933221144",
            rating: 4.2,
            totalRatings: 7,
        },
        userRating: {
            value: 5,
            comment: "Producto como nuevo, todo excelente.",
        },
    },
    {
        id: "p005",
        title: "Polerón Adidas gris",
        description: "Polerón deportivo con cierre, interior afelpado.",
        price: 9990,
        size: "XL",
        category: "polerones",
        images: [defaultImages.products[4], defaultImages.products[5]],
        status: "disponible",
        seller: {
            id: "u005",
            name: "Martina Rojas",
            email: "martina@mail.com",
            phone: "+56966778899",
            rating: 5.0,
            totalRatings: 3,
        },
        userRating: null,
    },
    {
        id: "p006",
        title: "Falda larga floreada",
        description: "Falda boho con flores, ideal para primavera.",
        price: 8990,
        size: "M",
        category: "faldas",
        images: [defaultImages.products[5], defaultImages.products[6]],
        status: "vendido",
        seller: {
            id: "u006",
            name: "Sofía Herrera",
            email: "sherrera@mail.com",
            phone: "+56955443322",
            rating: 4.6,
            totalRatings: 14,
        },
        userRating: {
            value: 4,
            comment: "Buena calidad, aunque la talla venía un poco ajustada.",
        },
    },
    {
        id: "p007",
        title: "Vestido negro clásico",
        description: "Vestido elegante para eventos, talla única.",
        price: 14990,
        size: "U",
        category: "vestidos",
        images: [defaultImages.products[6], defaultImages.products[7]],
        status: "disponible",
        seller: {
            id: "u007",
            name: "Francisca Muñoz",
            email: "fran.munoz@mail.com",
            phone: "+56999887766",
            rating: 4.3,
            totalRatings: 9,
        },
        userRating: null,
    },
    {
        id: "p008",
        title: "Camisa a cuadros Uniqlo",
        description: "Camisa semi-formal, algodón liviano.",
        price: 7900,
        size: "L",
        category: "camisas",
        images: [defaultImages.products[7], defaultImages.products[8]],
        status: "disponible",
        seller: {
            id: "u008",
            name: "Andrés Salas",
            email: "asalas@mail.com",
            phone: "+56955667788",
            rating: 4.0,
            totalRatings: 5,
        },
        userRating: null,
    },
];